import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.cluster import KMeans
from typing import List, Dict, Any
from app.models.schemas import RecommendationRequest, RecommendationItem, RecommendationResponse

class LearnerRecommendationEngine:
    """
    Real baseline recommendation engine powered by Scikit-Learn.
    - RandomForestClassifier: Predicts learner trajectory / intervention need
    - KMeans: Clusters learners into behavioral cohorts (Fast Pace, Balanced, Remedial)
    """

    def __init__(self):
        self.rf_model = None
        self.kmeans_model = None
        self._train_baseline_models()

    def _train_baseline_models(self):
        # Features: [average_score, attempts_count, time_spent_minutes, completion_rate, current_difficulty_level (1=Beg, 2=Int, 3=Adv)]
        # Target: 0 = "NEEDS_REMEDIAL", 1 = "REINFORCE_QUIZ", 2 = "ADVANCE_ROADMAP"
        np.random.seed(42)

        # Generate synthetic training observations
        # Class 0: Low scores, high attempts, low completion -> Remedial
        X_0 = np.column_stack([
            np.random.uniform(10, 49, 150),
            np.random.uniform(3, 8, 150),
            np.random.uniform(40, 120, 150),
            np.random.uniform(0.0, 0.3, 150),
            np.random.choice([1, 2], 150)
        ])
        y_0 = np.zeros(150)

        # Class 1: Mid scores (50-75%), moderate attempts -> Practice Quiz
        X_1 = np.column_stack([
            np.random.uniform(50, 74, 150),
            np.random.uniform(1, 4, 150),
            np.random.uniform(20, 60, 150),
            np.random.uniform(0.3, 0.7, 150),
            np.random.choice([1, 2, 3], 150)
        ])
        y_1 = np.ones(150)

        # Class 2: High scores (>75%), quick mastery -> Advance Roadmap
        X_2 = np.column_stack([
            np.random.uniform(75, 100, 150),
            np.random.uniform(1, 2, 150),
            np.random.uniform(15, 45, 150),
            np.random.uniform(0.7, 1.0, 150),
            np.random.choice([2, 3], 150)
        ])
        y_2 = np.full(150, 2)

        X = np.vstack([X_0, X_1, X_2])
        y = np.concatenate([y_0, y_1, y_2])

        self.rf_model = RandomForestClassifier(n_estimators=50, max_depth=5, random_state=42)
        self.rf_model.fit(X, y)

        # Fit KMeans clusterer for learner profiling (3 clusters: Remedial, Consistent, Accelerator)
        self.kmeans_model = KMeans(n_clusters=3, random_state=42, n_init=10)
        self.kmeans_model.fit(X[:, :3]) # cluster by [score, attempts, time]

    def predict_recommendations(self, request: RecommendationRequest) -> RecommendationResponse:
        avg_score = request.averageScore if request.averageScore > 0 else 55.0
        total_attempts = request.totalAttempts if request.totalAttempts > 0 else 1
        total_time = sum(p.timeSpentMinutes for p in request.topicProgress) if request.topicProgress else 30

        completed_count = sum(1 for p in request.topicProgress if p.masteryScore >= 70)
        total_topics = max(1, len(request.topicProgress))
        completion_rate = completed_count / total_topics

        # Learner feature vector
        features = np.array([[avg_score, total_attempts, total_time, completion_rate, 2]])
        intervention_class = int(self.rf_model.predict(features)[0])

        cluster_idx = int(self.kmeans_model.predict([[avg_score, total_attempts, total_time]])[0])
        cluster_labels = {0: "Remedial / Diligent", 1: "Balanced Achiever", 2: "Accelerated Learner"}
        learner_cohort = cluster_labels.get(cluster_idx, "Balanced Achiever")

        recommendations: List[RecommendationItem] = []

        # Analyze topic knowledge gaps
        weak_topics = [p for p in request.topicProgress if p.masteryScore < 50 or p.knowledgeLevel.upper() == "WEAK"]
        developing_topics = [p for p in request.topicProgress if 50 <= p.masteryScore < 75 or p.knowledgeLevel.upper() == "DEVELOPING"]

        if weak_topics:
            for wt in weak_topics[:2]:
                recommendations.append(RecommendationItem(
                    type="RESOURCE",
                    targetId=wt.topicId,
                    title=f"Review Core Concepts: {wt.topicTitle}",
                    reason=f"Model detected a knowledge gap ({wt.masteryScore:.0f}% mastery). Re-reading reference guides will build prerequisite strength.",
                    priorityScore=0.96,
                    clusterGroup=learner_cohort
                ))
                recommendations.append(RecommendationItem(
                    type="QUIZ",
                    targetId=wt.topicId,
                    title=f"Adaptive Diagnostic Quiz: {wt.topicTitle}",
                    reason="Targeted challenge generated by random forest classifier to verify retention.",
                    priorityScore=0.88,
                    clusterGroup=learner_cohort
                ))

        if developing_topics:
            for dt in developing_topics[:1]:
                recommendations.append(RecommendationItem(
                    type="QUIZ",
                    targetId=dt.topicId,
                    title=f"Level-Up Challenge: {dt.topicTitle}",
                    reason=f"Current score is {dt.masteryScore:.0f}%. Completing one more quiz with 75%+ will upgrade this topic to Proficient.",
                    priorityScore=0.82,
                    clusterGroup=learner_cohort
                ))

        # Add Next Roadmap Topic if available
        next_topic_id = 2
        next_topic_title = "Data Structures & Modern Algorithms"
        if request.topicProgress:
            highest_id = max(p.topicId for p in request.topicProgress)
            next_topic_id = highest_id + 1
            next_topic_title = f"Advanced Unit {next_topic_id}"

        recommendations.append(RecommendationItem(
            type="TOPIC",
            targetId=next_topic_id,
            title=f"Advance Roadmap: {next_topic_title}",
            reason=f"Recommended by Scikit-Learn pipeline for cohort '{learner_cohort}'.",
            priorityScore=0.75,
            clusterGroup=learner_cohort
        ))

        return RecommendationResponse(
            userId=request.userId,
            learnerProfile=learner_cohort,
            recommendations=recommendations
        )

# Global singleton
recommendation_engine = LearnerRecommendationEngine()
